package generala;

public class Menu {

	final String MENU_LOAD = "INGRESE EL NOMBRE DE LA PARTIDA GUARDADA";
	final String MENU_ERROR_LOAD = "AH OCURRIDO ALGUN ERROR, VOLVIENDO AL MENU";
	final String MENU_JUGAR = "GENERALA" + "\n" + "1-JUGAR" + "\n" + "2-LOAD" + "\n" + "3-SALIR DEL JUEGO";
	final String MENU_ERROR = "OPCION INCORRECTA, VUELVA A INTENTARLO";
	final String MENU_SAVE = "CON QUE NOMBRE QUIERE GUARDAR LA PARTIDA";
	final String MENU_SALIENDO = "SALIENDO AL MENU";
	final String MENU_JUGADA_ANOTADA = "JUGADA ANOTADA CON EXITO";
	final String MENU_CARGAR_CANT_JUGADORES = "GENERALA"+ "\n" + "Ingrese cantidad de jugadores:" + " 2,3 o 4 jugadores";
	final String CANTIDAD_INCORRECTA = "CANTIDAD INCORRECTA, VUELVA A INTENTARLO";
	final String MENU_REVERSE = "QUIERE USAR EL VALOR DE LA CARA OPUESTA DE LOS DADOS?:" + "\n" + "1-SI:" + "\n" + "2-NO:";
	final String MENU_TODOS_SEPARADOS = "SE HAN SEPARADO TODOS LOS DADOS, REINCORPORE DADOS O SALGA DEL MENU PRINCIPAL PARA CONTINUAR";
	final String VALOR_INEXISTENTE = "VALOR INEXISTENTE , VUELVE A INTENTAR O SALGA PARA CONTINUAR";
	final String MENU_PRINCIPAL = "1-SEPARAR:"+ "\n" +  "2-REINCORPORAR" + "\n" +"3-SUMAR" + "\n" +"4-TACHAR" + "\n" +"5-SAVE" + "\n" +"6-IMPRIMIR SEPARADOS" + "\n" +"7-IMPRIMIR TABLA RESULTADOS" + "\n" +"8-IMPRIMIR DADOS" + "\n" +"9-SALIR DEL JUEGO" + "\n" +"0-SALIR O CONTINUAR";
	final String VALOR_INEXISTENTE_2 = "VALOR INEXISTENTE , VUELVE A INTENTARLO";
	
	public Menu()
	{
		
	}
	
	public String getMENU_ERROR_LOAD() {
		return MENU_ERROR_LOAD;
	}
	
	public String getMENU_LOAD() {
		return MENU_LOAD;
	}


	
	
	
	
}
